### PR TITLE
Add Zarah Dominguez

### PR DESCRIPTION
**Pull request by zmdominguez**

### CODE REVIEW

**Review by chiuki — APPROVED** [review]
Merging this to add you to the list but please submit another PR to update the link to your speaking profile.

**Comment by zmdominguez** [comment]
(The page linked to has the speaking list in it now)

**Comment by chiuki** [comment]
@zmdominguez I searched for "speaking" and "talk" but didn't see the speaking list on http://zdominguez.com?

**Comment by zmdominguez** [comment]
Oh right! Sorry, yes you are correct. The link should point to About page -- http://zdominguez.com/about/ will make a separate PR.

**Pull request merged**
